# ==Tomcat配置==
server:
  port: 8087
  tomcat:
    max-connections: 20000 # 最大连接数 表示有多少个socket连接到tomcat上 NIO模式下默认是10000
    accept-count: 200 # 允许的最大连接数，即等待队列 应大于等于max-threads 默认值75
    max-threads: 2000     # 最大连接线程数 默认值75
    uri-encoding: UTF-8
    accesslog:
      enabled: true
      directory: /opt/logs/job-service/
      pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" %D'
  max-http-header-size: 10000000 #扩展 tomcat header的长度 omcat限制了header的长度,如果你请求的数据量超过了默认的长度就会抛出越界，

# 本服务需要调用的服务和授权信息-service层
base-service:
  sys-base-service: sys-base-service
  sys-kafka-service: sys-kafka-service
  sys-redis-service: sys-redis-service
  sys-es-service: sys-es-service
  name: serviceadmin
  password: service987423Ds887

eureka:
  # 链接eureka的用户名密码
  name: xmfadmin
  password: eureka-xmfp23dw
  client:
    serviceUrl:
      defaultZone:  http://${eureka.name}:${eureka.password}@localhost:8081/eureka/
    healthcheck:
      enabled: true                           # 开启健康检查（依赖spring-boot-starter-actuator）
    registry-fetch-interval-seconds: 1   # 表示eureka client间隔多久去拉取服务注册信息，刷新本地缓存时间 默认为30秒
    #Eureka服务注册中心也会尝试把自己当做客户端来注册自己，就会出现下面的错误
  # 灰度发布配置
  instance:
    metadata-map:
      gated-launch: false
    leaseRenewalIntervalInSeconds: 1     # 心跳时间，即服务续约间隔时间（缺省为30s）
    leaseExpirationDurationInSeconds: 2  # 发呆时间，即服务续约到期时间（缺省为90s）
spring:
  application:
    name: job-service
  cloud:
    loadbalancer:
      retry:
        enabled: true
  main:
    allow-bean-definition-overriding: true # 防止'${base-service: sys-base-service}.FeignClientSpecification', defined in null, could not be registered 多个接口请求服务名称相同
  sleuth:
    sampler:
      probability: 1 #收集日志比例 100%
# LOGGING
logging:
    config: classpath:logback.xml
# timeout config

# 配置ribbon 配置下列值并非ribbon get set 属性，因此鼠标点击无用，但是ribbon会自动加载以下信息
ribbon:
  NFLoadBalancerClassName: com.netflix.loadbalancer.DynamicServerListLoadBalancer  #负载均衡器
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule # 负载策略 ---权重策略---WeightedResponseTimeRule根据响应时间分配一个weight，响应时间越长，weight越小，被选中的可能性越低。
  OkToRetryOnAllOperations: false  # 是否所有操作都进行重试
  retryable: true #是否开启重试功能
  MaxAutoRetries: 0 #同一个Server重试的次数(除去首次)
  MaxAutoRetriesNextServer: 2 #切换相同Server的次数
  MaxHttpConnectionsPerHost: 200 #每个节点Http的最大连接数 默认值50
  MaxConnectionsPerHost: 200 #每个节点的最大连接数 默认值50
  MaxTotalHttpConnections: 2000  #http总连接数 默认值200
  MaxTotalConnections: 2000 # 总连接数 默认值200
  PoolMinThreads: 1 #线程池最小容量 默认值1 值范围1-10
  PoolMaxThreads: 300 #线程池最大容量 默认值 200 值范围200-400
  ConnectTimeout: 2000
  ReadTimeout: 20000 # ribbon 读取返回信息的超时时间，值范围30000-300000
  httpclient:
    enabled: true #okhttp替换httpclient OkHttp 会使用连接池来复用连接以提高效率。OkHttp 提供了对 GZIP 的默认支持来降低传输内容的大小。OkHttp 也提供了对 HTTP 响应的缓存机制，可以避免不必要的网络请求
  okhttp:
    enabled: false #okhttp替换httpclient OkHttp 会使用连接池来复用连接以提高效率。OkHttp 提供了对 GZIP 的默认支持来降低传输内容的大小。OkHttp 也提供了对 HTTP 响应的缓存机制，可以避免不必要的网络请求
  eager-load:
    enabled: true

#job任务配置
xmf:
  job:
    admin:
      addresses: http://localhost:8082/job #调度中心部署跟地址 多个逗号隔开
    executor:
      appname: xmf-job-timer #执行器"AppName"和地址信息配置：AppName执行器心跳注册分组依据
      ip:        #执行器IP默认为空表示自动获取IP，多网卡时可手动设置指定IP，手动设置IP时将会绑定Host
      port: 9999     #执行器默认端口为9999
      logpath: /opt/logs/job-service/task   #执行器运行日志文件存储的磁盘位置，需要对该路径拥有读写权限
      logretentiondays: 3 #执行器Log文件定期清理功能，指定日志保存天数，日志文件过期自动删除。限制至少保持3天，否则功能不生效；
    accessToken: 123456  #执行器通讯TOKEN，非空时启用

kafka:
  server: 10.105.10.12:9092
  consumer:
    groupId: xmf_cn
    auto_offset_reset: latest # earliest 当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，从头开始消费 latest 当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，消费新产生的该分区下的数据
    enableAutoCommit: false
    maxPollIntervalMs: 120000 # 两次poll()的间隔若大于该配置时间，如果此超时时间期满之前poll()没有调用，则消费者被视为失败，并且分组将重新平衡，以便将分区重新分配给别的成员。
    sessionTimeoutMs: 180000 # 如果消费者崩溃或无法在session.timeout.ms配置的时间内发送心跳，则消费者将被视为死亡，并且其分区将被重新分配。
    maxPollRecords: 500 # 单次拉取的最大消息数量
    keyDeserializerClass: org.apache.kafka.common.serialization.StringDeserializer
    valueDeserializerClass: org.apache.kafka.common.serialization.StringDeserializer